import Head from "next/head";
import Homepage from "../Components/Homepage";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,700&display=swap"
          rel="stylesheet"
          defer
        />
      </Head>

      <main>
        <Homepage />
      </main>
    </div>
  );
}
